# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pentagram', '0004_photolike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='like',
        ),
        migrations.AlterUniqueTogether(
            name='photolike',
            unique_together=set([('photo', 'user')]),
        ),
    ]
